name: conc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  # Core ML Libraries
  - numpy>=1.19.5,<1.20.0  # Maintaining compatibility with existing model
  - pandas>=1.3.3,<1.4.0
  - scikit-learn>=0.24.2,<0.25.0
  - xgboost=2.0.3  # Specific version for Apple Silicon compatibility
  - statsmodels>=0.12.2,<0.13.0
  # Web Framework
  - gunicorn>=20.1.0
  # Utils
  - joblib>=1.0.1,<1.1.0
  - requests>=2.26.0
  - pip:
    # Any packages that might not be available in conda channels
    - python-dotenv>=0.19.0  # For environment variable management
    - fastapi>=0.68.0  # Modern web framework replacement for Flask
    - uvicorn>=0.15.0  # ASGI server for FastAPI
    - python-multipart  # For form data handling in FastAPI
    - jinja2>=3.0.0  # For template rendering
